<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'state\\orderfacadetest' => '/OrderFacadeTest.php',
                'state\\states\\cancelorderstatetest' => '/States/CancelOrderStateTest.php',
                'state\\states\\deliverorderstatetest' => '/States/DeliveredOrderStateTest.php',
                'state\\states\\orderdonestatetest' => '/States/OrderDoneStateTest.php',
                'state\\states\\paidorderstatetest' => '/States/PaidOrderStateTest.php',
                'state\\states\\processorderstatetest' => '/States/ProcessOrderStateTest.php',
                'state\\states\\returnorderstatetest' => '/States/ReturnOrderStateTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
