<?php

namespace State\States
{
    class InitialStateTestTest extends \PHPUnit_Framework_TestCase
    {
        protected function setUp()
        {
             //TODO: Change the autogenerated stub
        }
    }
}
