<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'state\\orderfacade' => '/OrderFacade.php',
                'state\\orderinterface' => '/OrderInterface.php',
                'state\\states\\cancelorderstate' => '/States/CancelOrderState.php',
                'state\\states\\deliverorderstate' => '/States/DeliveredOrderState.php',
                'state\\states\\orderdonestate' => '/States/OrderDoneState.php',
                'state\\states\\paidorderstate' => '/States/PaidOrderState.php',
                'state\\states\\processorderstate' => '/States/ProcessOrderState.php',
                'state\\states\\returnorderstate' => '/States/ReturnOrderState.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
